### ISSUE TITLE
Open discuss

### ISSUE THREAD

**Issue by luisadha** [BoboiAzumi/BacaManga#1]
Cara pakainya gimana puh

**Comment by BoboiAzumi** [comment]
Tinggal di clone ke folder project netbeansnya puh
o iya sesuain juga versi jdknya, gw pake jdk versi 17 kalau gak salah

**Comment by BoboiAzumi** [comment]
kira kira di 
C:\Users\<users>\Documents\NetBeansProjects

**Comment by luisadha** [comment]
Terima kasih puh
